environments:
  default: {}
  development: {}
---
releases:
- name: eden-worker-deployment
  namespace: eden-worker
  chart: ../charts/deployment
  installed: true
  values:
  - deployment/values.yaml
  - deployment/{{ .Environment.Name }}_values.yaml
