load('ext://namespace', 'namespace_inject')

NAMESPACE='flower'

k8s_yaml(namespace_inject(read_file('./deployment/deployment.yaml'), NAMESPACE))
k8s_resource(
    'flower',
    resource_deps=['redis-master'],
    port_forwards=[
        port_forward(5555, 5555, name='tasks', link_path='/tasks'),
    ]
)
