load('ext://namespace', 'namespace_create', 'namespace_inject')
load('ext://nerdctl', 'nerdctl_build')
load('ext://secret', 'secret_yaml_generic')

NAMESPACE='flower'
namespace_create(NAMESPACE)

k8s_yaml(secret_yaml_generic('flower-secret-env', from_env_file='./.env', namespace=NAMESPACE))
k8s_yaml(namespace_inject(read_file('./deployment/deployment.yaml'), NAMESPACE))
k8s_resource('flower', resource_deps=['redis-master'])
