environments:
  default: {}
  development: {}
---
releases:
  - name: heimdall-deployment
    namespace: heimdall
    chart: ../charts/deployment
    labels:
      type: deployment
    installed: true
    values:
      - deployment/values.yaml
      - deployment/{{ .Environment.Name }}_values.yaml
    {{ $hosts := requiredEnv "ALLOWED_HOSTS" }}
    {{ if eq .Environment.Name "default" }}
    {{ $header_list := split "," $hosts }}
    {{ $header := index $header_list "_0" }}
      - livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
            httpHeaders:
              - name: Host
                value: {{ $header }}
          initialDelaySeconds: 5
          periodSeconds: 10
      - readinessProbe:
          httpGet:
            path: /readiness
            port: 8000
            httpHeaders:
              - name: Host
                value: {{ $header }}
          initialDelaySeconds: 5
          periodSeconds: 10
    {{ end }}
      - env:
          # * load base environment variables here *
          {{ $fileContent := readFile "./deployment/env/base_env.yaml" | fromYaml  }}
          {{ range $index,$item := index $fileContent "env" }}
          - name: {{ index $item "name" }}
            value: {{ index $item "value"}}
          {{ end }}
          # * load environment specific environment variables here *
          {{ $envFile := join "" (list "./deployment/env/" .Environment.Name "_env.yaml") }}
          {{ $fileContent := readFile $envFile | fromYaml  }}
          {{ range $index,$item := index $fileContent "env" }}
          - name: {{ index $item "name" }}
            value: {{ index $item "value"}}
          {{ end }}
          # * environment variables that need template fxns go here *
          - name : ALLOWED_HOSTS
            value: {{ $hosts }}

  - name: heimdall-apis
    namespace: heimdall
    chart: ../charts/api
    labels:
      type: api
    installed: true
    values:
      - api/values.yaml
    needs:
      - heimdall-deployment
