releases:
- name: heimdall-deployment
  namespace: heimdall
  chart: ../charts/deployment
  installed: true
  values:
  - deployment/values.yaml
- name: heimdall-apis
  namespace: heimdall
  chart: ../charts/api
  installed: true
  values:
  - api/values.yaml
  needs:
  - heimdall-deployment

