environments:
  default: {}
  development: {}
---
releases:
- name: heimdall-deployment
  namespace: heimdall
  chart: ../charts/deployment
  labels:
    type: deployment
  installed: true
  values:
  - deployment/values.yaml
  - deployment/{{ .Environment.Name }}_values.yaml
- name: heimdall-apis
  namespace: heimdall
  chart: ../charts/api
  labels:
    type: api
  installed: true
  values:
  - api/values.yaml
  needs:
  - heimdall-deployment

