apiVersion: v1
kind: Service
metadata:
  name: heimdall-svc
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: heimdall-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimdall-svc
      version: v1
  template:
    metadata:
      labels:
        app: heimdall-svc
        version: v1
    spec:
      containers:
      - name: heimdall-svc
        image: heimdall-svc-img
        ports:
        - containerPort: 8000
---
