load('ext://namespace', 'namespace_inject')
load('ext://podman', 'podman_build')
load('ext://uibutton', 'cmd_button', 'location', 'choice_input')

NAMESPACE = 'heimdall'
TILT_PATH = '../../../tilt/heimdall'

k8s_yaml(namespace_inject(read_file('{0}/deployment/deployment.yaml'.format(TILT_PATH)), NAMESPACE))
k8s_yaml(namespace_inject(read_file('{0}/deployment/service.yaml'.format(TILT_PATH)), NAMESPACE))

k8s_resource(
    'heimdall-svc',
    labels=["auth"],
    # UNCOMMENT to test just api locally
    # port_forwards=8000 
    # DEFAULT expose admin page
    port_forwards=[
        port_forward(8000, 8000, name='admin', link_path='/admin'),
    ],
    resource_deps=['migrate-heimdall']
)

k8s_yaml(namespace_inject(read_file('{0}/api/apidefinition-heimdall-api.yaml'.format(TILT_PATH)), NAMESPACE))
k8s_yaml(namespace_inject(read_file('{0}/api/apidefinition-heimdall-all-auth.yaml'.format(TILT_PATH)), NAMESPACE))

k8s_resource(
  objects=['heimdall-api:apidefinition'],
  new_name='heimdall-api',
  labels=['api-gateway'],
  resource_deps=['tyk-operator-ready']
)

k8s_resource(
  objects=['heimdall-all-auth:apidefinition'],
  new_name='heimdall-all-auth',
  labels=['api-gateway'],
  resource_deps=['tyk-operator-ready']
)

podman_build('localhost:5001/heimdall-svc-img', '.',     
    live_update=[
        sync('./heimdall', '/code/heimdall'),
        run('cd /code && poetry install --no-interaction --no-root --without dev',
            trigger=['./poetry.lock', './pyproject.toml']),
    ]
)

cmd_button(
  name='manage-btn',
  argv=['sh', '-c', 'cd apps/microservices/heimdall && export ENVIRONMENT=local && export ALLOWED_HOSTS=localhost && poetry install && poetry run python manage.py $command'],
  text='heimdall manage',
  location=location.RESOURCE,
  inputs=[
    choice_input('command', label='command', choices=[
        'makemigrations',
        'migrate',
    ])
  ],
  resource='heimdall-svc',
  icon_name='sync_alt'
)