---
# Source: api/templates/apidefinitions.yaml
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: heimdall-api
spec:
  name: heimdall-api
  use_keyless: true
  protocol: http
  active: true
  proxy:
    target_url: http://heimdall-svc.heimdall.svc:8000
    listen_path: /api/auth/
    strip_listen_path: true
  CORS:
    enable: true
    allowed_origins:
    - "http://localhost:4200"
    allowed_methods:
    - "GET"
    - "POST"
    - "OPTIONS"
    allowed_headers: []
    exposed_headers: []
    allow_credentials: false
    max_age: 24
    options_passthrough: false
---
# Source: api/templates/delete-api-jobs.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: delete-apis-job
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: delete-apis
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              # Delete APIs
              kubectl delete apidefinition.tyk.tyk.io --all --namespace heimdall

              # Remove finalizers
              for api in $(kubectl get apidefinition.tyk.tyk.io -o jsonpath='{.items[*].metadata.name}' --namespace heimdall); do
                kubectl patch apidefinition.tyk.tyk.io $api --type=json -p='[{"op": "remove", "path": "/metadata/finalizers"}]' --namespace heimdall
              done
      restartPolicy: OnFailure

