---
# Source: deployment/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eden-worker
  labels:
    helm.sh/chart: deployment-0.1.0
    app.kubernetes.io/name: eden-worker
    app.kubernetes.io/instance: eden-worker-deployment
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: eden-worker
      app.kubernetes.io/instance: eden-worker-deployment
  template:
    metadata:
      labels:
        helm.sh/chart: deployment-0.1.0
        app.kubernetes.io/name: eden-worker
        app.kubernetes.io/instance: eden-worker-deployment
        app.kubernetes.io/managed-by: Helm
    spec:
      securityContext:
        {}
      containers:
        - name: eden-worker
          securityContext:
            {}
          image: "localhost:5001/eden-worker-img:latest"
          env:
            - name: CELERY_BROKER_URL
              valueFrom:
                secretKeyRef:
                  key: CELERY_BROKER_URL
                  name: eden-worker-secret-env
            - name: CELERY_RESULT_BACKEND
              valueFrom:
                secretKeyRef:
                  key: CELERY_RESULT_BACKEND
                  name: eden-worker-secret-env
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: http://opentelemetry-collector.otel-collector.svc.cluster.local/v1/traces
            - name: ENVIRONMENT
              value: local
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 512Mi
