apiVersion: apps/v1
kind: Deployment
metadata:
  name: eden-svc
  labels:
    app: eden-svc
spec:
  selector:
    matchLabels:
      app: eden-svc
  template:
    metadata:
      labels:
        app: eden-svc
    spec:
      containers:
        - name: eden-svc
          image: eden-svc-img
          ports:
            - containerPort: 7079
---
apiVersion: v1
kind: Service
metadata:
  name: eden-svc
spec:
  selector:
    app: eden-svc
  ports:
    - protocol: TCP
      port: 7079
      targetPort: 7079
