apiVersion: v1
kind: Service
metadata:
  name: eden-svc
spec:
  ports:
  - name: http
    port: 7079
    targetPort: 7079
  selector:
    app: eden-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eden-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eden-svc
      version: v1
  template:
    metadata:
      labels:
        app: eden-svc
        version: v1
    spec:
      containers:
      - name: eden-svc
        image: eden-svc-img
        ports:
        - containerPort: 7079
---
