[tool.coverage.run]
branch = true
source = [ "eden" ]

[tool.coverage.report]
exclude_lines = ['if TYPE_CHECKING:']
show_missing = true

[tool.poetry]
name = "polytlk-eden"
version = "1.0.0"
description = "Eden: microservice for chinese NLP"
authors = [ ]
license = 'Proprietary'
readme = 'README.md'

[[tool.poetry.packages]]
include = "eden"

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
fastapi = "^0.95.2"
uvicorn = {extras = ["standard"], version = "^0.22.0"}
hanlp = "^2.1.0b50"
lingua-language-detector = "^1.3.2"

[tool.poetry.group.dev.dependencies]
autopep8 = "2.0.0"
wemake-python-styleguide = {git = "https://github.com/wemake-services/wemake-python-styleguide.git"}
pytest = "^7.3.2"
hypothesis = "^6.77.0"

[tool.poetry.scripts]
start = "eden.asgi:start"

[build-system]
requires = ["poetry-core==1.1.0"]
build-backend = "poetry.core.masonry.api"
