[tool.coverage.run]
branch = true
source = [ "eden" ]

[tool.coverage.report]
exclude_lines = ['if TYPE_CHECKING:']
show_missing = true

[tool.pytest.ini_options]
addopts = "--cov --cov-fail-under=100 --cov-report html:'../../../coverage/apps/microservices/eden/html' --cov-report xml:'../../../coverage/apps/microservices/eden/coverage.xml' --junitxml='../../../reports/apps/microservices/eden/unittests/junit.xml' --html='../../../reports/apps/microservices/eden/unittests/html/index.html'"

[tool.poetry]
name = "polytlk-eden"
version = "1.0.0"
description = "Eden: microservice for chinese nlp"
authors = [ ]
license = 'Proprietary'
readme = 'README.md'

[[tool.poetry.packages]]
include = "eden"

[tool.poetry.dependencies]
python = ">=3.11"
fastapi = "^0.95.2"
uvicorn = {extras = ["standard"], version = "^0.22.0"}
hanlp = "^2.1.0b50"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"

[tool.poetry.scripts]
start = "eden.asgi:start"

[build-system]
requires = ["poetry-core==1.1.0"]
build-backend = "poetry.core.masonry.api"
