---
# Source: deployment/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flower
  labels:
    helm.sh/chart: deployment-0.1.0
    app.kubernetes.io/name: flower
    app.kubernetes.io/instance: flower-deployment
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 5555
      targetPort: 5555
      protocol: TCP
  selector:
    app.kubernetes.io/name: flower
    app.kubernetes.io/instance: flower-deployment
