/* eslint-disable @typescript-eslint/consistent-type-definitions */
// Generated by '@import-meta-env/typescript'

interface ImportMetaEnv {
  readonly BASE_URL: string;
  readonly TARGET_ENV: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
