load('ext://helm_resource', 'helm_resource')

# define tyk namespace
tyk_namespace = 'tyk'

# create the namespace using local command and kubectl
local('kubectl create namespace {} || true'.format(tyk_namespace))

k8s_yaml('policy-configmap.yaml')
# created with 
# kubectl create configmap sse-auth-pre-middleware --from-file=./k8s/tyk/middleware/sse-auth-pre-middleware.js --append-hash=true --dry-run=client -o yaml > ./k8s/tyk/ce/sse-auth-pre-middleware.yaml
k8s_yaml('sse-auth-pre-middleware.yaml')

local('kubectl apply -f policy-configmap.yaml -n tyk')
local('kubectl apply -f sse-auth-pre-middleware.yaml -n tyk')

helm_resource(
    name='tyk-headless',
    chart='tyk-helm/tyk-headless',
    release_name='tyk-headless',
    namespace=tyk_namespace,
    flags=['--values=./tyk.yaml'],
    labels=['api-gateway'],
    resource_deps=['tyk-helm'],
    port_forwards='8080'
)
