---
# Source: deployment/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall-svc
  labels:
    helm.sh/chart: deployment-0.1.0
    app.kubernetes.io/name: heimdall-svc
    app.kubernetes.io/instance: heimdall-deployment
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: heimdall-svc
      app.kubernetes.io/instance: heimdall-deployment
  template:
    metadata:
      labels:
        helm.sh/chart: deployment-0.1.0
        app.kubernetes.io/name: heimdall-svc
        app.kubernetes.io/instance: heimdall-deployment
        app.kubernetes.io/managed-by: Helm
    spec:
      securityContext:
        null
      containers:
        - name: heimdall-svc
          securityContext:
            null
          image: "localhost:5001/heimdall-svc-img:latest"
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            - name: DJANGO_SECRET
              valueFrom:
                secretKeyRef:
                  key: DJANGO_SECRET
                  name: heimdall-svc-secret-env
            - name: TYK_MANAGEMENT_API_KEY
              valueFrom:
                secretKeyRef:
                  key: TYK_MANAGEMENT_API_KEY
                  name: heimdall-svc-secret-env
            - name: GOOGLE_SECRET
              valueFrom:
                secretKeyRef:
                  key: GOOGLE_SECRET
                  name: heimdall-svc-secret-env
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: DB_PASS
                  name: heimdall-svc-secret-env
            - name: ALLOWED_HOSTS
              value: heimdall-svc.heimdall.svc,localhost
            - name: SERVICE_NAME
              value: heimdall-service
            - name: GATEWAY_HOST
              value: gateway-svc-tyk.tyk.svc.cluster.local
            - name: EDEN_API_ID
              value: ZWRlbi9lZGVuLWFwaQ
            - name: ENVIRONMENT
              value: local
            - name: GATEWAY_PORT
              value: "8080"
            - name: CLIENT_ID_WEB
              value: 540933041586-61juofou98dd54ktk134ktfec2c84gd3.apps.googleusercontent.com
            - name: CLIENT_ID_IOS
              value: 540933041586-83lavib8c5hu16r0v6g63200jdruif77.apps.googleusercontent.com
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: http://opentelemetry-collector.otel-collector.svc.cluster.local/v1/traces
            - name: GOOGLE_CLIENT_ID
              value: 540933041586-61juofou98dd54ktk134ktfec2c84gd3.apps.googleusercontent.com
            - name: DB_HOST
              value: postgresql.default.svc.cluster.local
            - name: DB_PORT
              value: "5432"
      nodeSelector:
        role: app
