{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.tls.secretName }}
type: kubernetes.io/tls
data:
    tls.crt: {{ .Values.tls.cert }}
    tls.key: {{ .Values.tls.key }}
{{- end }}
