apiVersion: apps/v1
kind: Deployment
metadata:
  name: olivia-svc
  labels:
    app: olivia-svc
spec:
  selector:
    matchLabels:
      app: olivia-svc
  template:
    metadata:
      labels:
        app: olivia-svc
    spec:
      containers:
        - name: olivia-svc
          image: olivia-svc-img
          ports:
            - containerPort: 6079
---
apiVersion: v1
kind: Service
metadata:
  name: olivia-svc
spec:
  selector:
    app: olivia-svc
  ports:
    - protocol: TCP
      port: 6079
      targetPort: 6079