load('ext://nerdctl', 'nerdctl_build')

k8s_yaml('kubernetes.yaml')
k8s_resource('olivia-svc', port_forwards=6079)

nerdctl_build('olivia-svc-img', '.',     
    live_update=[
        sync('.', '/code'),
        run('cd /code && poetry install --no-interaction --no-root --without dev',
            trigger=['./poetry.lock', './pyproject.toml']),
    ]
)


