load('ext://namespace', 'namespace_create', 'namespace_inject')
load('ext://helm_remote', 'helm_remote')

NAMESPACE='tyk'
namespace_create(NAMESPACE)

# created with 
# kubectl create configmap sse-auth-pre-middleware --from-file=./middleware/sse-auth-pre-middleware.js --append-hash=true --dry-run=client -o yaml > ./k8s/tyk/ce/sse-auth-pre-middleware.yaml
k8s_yaml(namespace_inject(read_file("./deps/policy-configmap.yaml"), NAMESPACE))
k8s_yaml(namespace_inject(read_file("./deps/sse-auth-pre-middleware.yaml"), NAMESPACE))

helm_remote(
    chart='tyk-oss',
    repo_name='tyk-helm',
    repo_url='https://helm.tyk.io/public/helm/charts/',
    namespace=NAMESPACE,
    version="1.6.0",
    values="./values.yaml"
)

k8s_resource(
  workload='gateway-tyk',
  new_name='tyk-gateway',
  labels=['api-gateway'],
  resource_deps=['redis-master'],
  port_forwards=8080
)