load('ext://namespace', 'namespace_create', 'namespace_inject')

namespace_create('tyk')

# created with 
# kubectl create configmap sse-auth-pre-middleware --from-file=./middleware/sse-auth-pre-middleware.js --append-hash=true --dry-run=client -o yaml > ./k8s/tyk/ce/sse-auth-pre-middleware.yaml
k8s_yaml(namespace_inject(read_file("./dependencies/policy-configmap.yaml"), 'tyk'))
k8s_yaml(namespace_inject(read_file("./dependencies/sse-auth-pre-middleware.yaml"), 'tyk'))
k8s_yaml(namespace_inject(read_file("./dependencies/tyk-operator-conf.yaml"), 'tyk'))

k8s_yaml(namespace_inject(read_file("./gateway/deployment-gw-repset.yaml"), 'tyk'))
k8s_yaml(namespace_inject(read_file("./gateway/secrets.yaml"), 'tyk'))
k8s_yaml(namespace_inject(read_file("./gateway/service-gw.yaml"), 'tyk'))

k8s_resource(
  workload='gateway-tyk',
  new_name='tyk-gateway',
  labels=['api-gateway'],
  resource_deps=['redis-master'],
  port_forwards=8080
)

k8s_yaml(namespace_inject(read_file("./operator/crds/crds.yaml"), 'tyk'))
k8s_yaml(namespace_inject(read_file("./operator/deployment/all.yaml"), 'tyk'))

k8s_resource(
  workload='tyk-operator-controller-manager',
  new_name='tyk-operator',
  labels=['ops'],
  resource_deps=['tyk-gateway']
)
