operatorSecret:
  enabled: false
global:
  components:
    operator: false
  servicePorts:
    gateway: 80
  secrets:
    useSecretName: "tyk-secrets-tyk-api-secret"
  redis:
    addrs:
      - vultr-prod-d47b69c5-e2a2-45ec-87e7-0ea500632c3e-vultr-prod-e0ea.vultrdb.com:16752
    passSecret:
      name: "tyk-secrets-redis-pass"
      keyName: "REDIS_PASS"
    useSSL: true
    storage:
      database: 0
tyk-gateway:
  fullnameOverride: "tyk"
  gateway:
    hostName: tyk-gw.local
    kind: Deployment
    replicaCount: 1
    image:
      repository: docker.tyk.io/tyk-gateway/tyk-gateway
      tag: v5.5.0
    initContainers:
      setupDirectories:
        repository: busybox
        tag: 1.32
    containerPort: 8080
    ingress:
      enabled: true
      className: "nginx"
      annotations: {}
      hosts:
        - host: dev.api.polytlk.io
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: gateway-svc-tyk
                  port:
                    number: 80
      tls:
      - secretName: tyk-secrets-tls-secret
        hosts:
         - dev.api.polytlk.io
    opentelemetry:
      enabled: true
      exporter: http
      endpoint: http://opentelemetry-collector.opentelemetry.svc.cluster.local/v1/traces
      headers: {}
      connectionTimeout: 1
      resourceName: tyk-api-gateway
      spanProcessorType: batch
      contextPropagation: tracecontext
    extraEnvs:
      - name: TYK_GW_ENABLEJSVM
        value: "true"
      - name: TYK_GW_LOGLEVEL
        value: "info"
      - name: TYK_GW_POLICIES_POLICYSOURCE
        value: "file"
      - name: TYK_GW_POLICIES_POLICYRECORDNAME
        value: /mnt/tyk-gateway/policies/policies.json
    extraVolumes:
      - name: policy-config
        configMap:
          name: policy-config
      - name: sse-auth-pre-middleware
        configMap:
          name: sse-auth-pre-middleware-tbmcf478cg
    extraVolumeMounts:
      - name: policy-config
        mountPath: "/mnt/tyk-gateway/policies"
        readOnly: true
      - name: sse-auth-pre-middleware
        mountPath: "/mnt/tyk-gateway/middleware"
        readOnly: true