nameOverride: ""
fullnameOverride: ""
secrets:
  APISecret: CHANGEME
  useSecretName: ""
  secrets.OrgID: "5e9d9544a1dcd60001d0ed20"
backend: ""
gateway:
  hostName: tyk-gw.local
  tls: false
  kind: Deployment
  replicaCount: 1
  containerPort: 8080
  image:
    repository: docker.tyk.io/tyk-gateway/tyk-gateway
    tag: v5.0.0
    pullPolicy: IfNotPresent
  control:
    enabled: false
    containerPort: 9696
    port: 9696
    type: ClusterIP
    annotations: {}
  service:
    type: ClusterIP
    port: 8080
    annotations: {}
  ingress:
    enabled: false
  extraEnvs:
  - name: TYK_GW_ENABLEJSVM
    value: "true"
  - name: TYK_GW_LOGLEVEL
    value: "info"
  - name: TYK_GW_POLICIES_POLICYSOURCE
    value: "file"
  - name: TYK_GW_POLICIES_POLICYPATH
    value: ""
  - name: TYK_GW_POLICIES_POLICYRECORDNAME
    value: /mnt/tyk-gateway/policies/policies.json
  extraVolumes:
  - name: policy-config
    configMap:
      name: policy-config
  - name: sse-auth-pre-middleware
    configMap:
      name: sse-auth-pre-middleware-tbmcf478cg
  extraVolumeMounts:
  - name: policy-config
    mountPath: "/mnt/tyk-gateway/policies"
    readOnly: true
  - name: sse-auth-pre-middleware
    mountPath: "/mnt/tyk-gateway/middleware"
    readOnly: true
  mounts: []
