nameOverride: ""
fullnameOverride: ""
secrets:
  APISecret: CHANGEME
  useSecretName: ""
  secrets.OrgID: "5e9d9544a1dcd60001d0ed20"
backend: ""
gateway:
  hostName: tyk-gw.local
  tls: true
  kind: Deployment
  replicaCount: 1
  containerPort: 8080
  image:
    repository: docker.tyk.io/tyk-gateway/tyk-gateway
    tag: v5.0.0
    pullPolicy: IfNotPresent
  control:
    enabled: false
    containerPort: 9696
    port: 9696
    type: ClusterIP
    annotations: {}
  service:
    type: LoadBalancer
    port: 443
    annotations: {
      gateway.service.annotations.service.beta.kubernetes.io/vultr-loadbalancer-protocol: "https"
    }
  ingress:
    enabled: false
  resources: {}
  securityContext:
    runAsUser: 1000
    fsGroup: 2000
  extraEnvs:
  - name: TYK_GW_ENABLEJSVM
    value: "true"
  - name: TYK_GW_LOGLEVEL
    value: "debug"
  - name: TYK_GW_POLICIES_POLICYSOURCE
    value: "file"
  - name: TYK_GW_POLICIES_POLICYPATH
    value: ""
  - name: TYK_GW_POLICIES_POLICYRECORDNAME
    value: /mnt/tyk-gateway/policies/policies.json
  - name: TYK_GW_HTTPSERVEROPTIONS_SSLCERTIFICATES
    value: /mnt/certs
  - name: TYK_GW_TRACK404LOGS
    value: true
  extraVolumes:
  - name: policy-config
    configMap:
      name: policy-config
  - name: sse-auth-pre-middleware
    configMap:
      name: sse-auth-pre-middleware-tbmcf478cg
  - name: gateway-tls-all
    projected:
      sources:
      - secret:
          name: gateway-tls
          items:
            - key: tls.key
              path: key.pem
      - secret: 
          name: gateway-tls
          items:
            - key: tls.crt
              path: cert.pem
  extraVolumeMounts:
  - name: policy-config
    mountPath: "/mnt/tyk-gateway/policies"
    readOnly: true
  - name: sse-auth-pre-middleware
    mountPath: "/mnt/tyk-gateway/middleware"
    readOnly: true
  - name: gateway-tls-all
    mountPath: "/mnt/certs"
    readOnly: true
  mounts: []
