load('ext://helm_remote', 'helm_remote')

helm_remote(
  'ingress-nginx',
  repo_name='ingress-nginx',
  repo_url='https://kubernetes.github.io/ingress-nginx',
  namespace="ingress-nginx",
  version="4.11.2",
  values="./values.yaml",
)

k8s_resource(
  workload="ingress-nginx-admission-create",
  labels=['nginx-controller']
)


k8s_resource(
  workload="ingress-nginx-controller",
  labels=['nginx-controller'],
  resource_deps=["ingress-nginx-admission-create"]
)

k8s_resource(
  objects=['ingress-nginx-admission:ValidatingWebhookConfiguration:ingress-nginx'],
  new_name="ingress-nginx-admission-webhook",
  labels=['nginx-controller'],
  resource_deps=["ingress-nginx-controller"]
)

k8s_resource(
  workload="ingress-nginx-admission-patch",
  labels=['nginx-controller'],
  resource_deps=["ingress-nginx-admission-webhook"]
)
