repositories:
- name: tyk-helm
  url: https://helm.tyk.io/public/helm/charts/

releases:
- name: tyk-headless
  namespace: tyk
  chart: tyk-helm/tyk-headless
  values:
  - tyk-headless-values.yaml

- name: tyk-operator
  namespace: tyk
  chart: tyk-helm/tyk-operator

