k8s_yaml('kubernetes.yaml')
k8s_resource('example-python', port_forwards=8079)

docker_build('example-python-image', '.',     
    live_update=[
        sync('.', '/code'),
        run('cd /app && poetry install --no-interaction --no-root --without dev',
            trigger='./poetry.lock'),
    ]
)


