image:
  repository: "ewr.vultrcr.com/polytlk/eden"
  tag: "sha-5e3ec4f"
env:
- name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
  value: "http://opentelemetry-collector.opentelemetry.svc.cluster.local/v1/traces"
- name: ENVIRONMENT
  value: "development"
livenessProbe:
  httpGet:
    path: /healthz
    port: 7079
  initialDelaySeconds: 5
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /readiness
    port: 7079
  initialDelaySeconds: 5
  periodSeconds: 10
