k8s_yaml('./eden.yaml')
k8s_resource(
  objects=['eden-api:apidefinition'],
  new_name='eden-api',
  labels=['api-gateway'],
  resource_deps=['tyk-operator']
)

k8s_yaml('./heimdall.yaml')
k8s_resource(
  objects=['heimdall-api:apidefinition'],
  new_name='heimdall-api',
  labels=['api-gateway'],
  resource_deps=['tyk-operator']
)
