-- Create "auth_user" table
CREATE TABLE "public"."auth_user" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "password" character varying(128) NOT NULL,
  "last_login" timestamptz NULL,
  "is_superuser" boolean NOT NULL,
  "username" character varying(150) NOT NULL,
  "first_name" character varying(150) NOT NULL,
  "last_name" character varying(150) NOT NULL,
  "email" character varying(254) NOT NULL,
  "is_staff" boolean NOT NULL,
  "is_active" boolean NOT NULL,
  "date_joined" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "auth_user_username_key" UNIQUE ("username")
);
-- Create index "auth_user_username_6821ab7c_like" to table: "auth_user"
CREATE INDEX "auth_user_username_6821ab7c_like" ON "public"."auth_user" ("username" varchar_pattern_ops);
-- Create "django_session" table
CREATE TABLE "public"."django_session" (
  "session_key" character varying(40) NOT NULL,
  "session_data" text NOT NULL,
  "expire_date" timestamptz NOT NULL,
  PRIMARY KEY ("session_key")
);
-- Create index "django_session_expire_date_a5c62663" to table: "django_session"
CREATE INDEX "django_session_expire_date_a5c62663" ON "public"."django_session" ("expire_date");
-- Create index "django_session_session_key_c0390e0f_like" to table: "django_session"
CREATE INDEX "django_session_session_key_c0390e0f_like" ON "public"."django_session" ("session_key" varchar_pattern_ops);
-- Create "account_emailaddress" table
CREATE TABLE "public"."account_emailaddress" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "email" character varying(254) NOT NULL,
  "verified" boolean NOT NULL,
  "primary" boolean NOT NULL,
  "user_id" integer NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "account_emailaddress_user_id_email_987c8728_uniq" UNIQUE ("user_id", "email"),
  CONSTRAINT "account_emailaddress_user_id_2c513194_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "account_emailaddress_email_03be32b2" to table: "account_emailaddress"
CREATE INDEX "account_emailaddress_email_03be32b2" ON "public"."account_emailaddress" ("email");
-- Create index "account_emailaddress_email_03be32b2_like" to table: "account_emailaddress"
CREATE INDEX "account_emailaddress_email_03be32b2_like" ON "public"."account_emailaddress" ("email" varchar_pattern_ops);
-- Create index "account_emailaddress_user_id_2c513194" to table: "account_emailaddress"
CREATE INDEX "account_emailaddress_user_id_2c513194" ON "public"."account_emailaddress" ("user_id");
-- Create index "unique_primary_email" to table: "account_emailaddress"
CREATE UNIQUE INDEX "unique_primary_email" ON "public"."account_emailaddress" ("user_id", "primary") WHERE "primary";
-- Create index "unique_verified_email" to table: "account_emailaddress"
CREATE UNIQUE INDEX "unique_verified_email" ON "public"."account_emailaddress" ("email") WHERE verified;
-- Create "account_emailconfirmation" table
CREATE TABLE "public"."account_emailconfirmation" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created" timestamptz NOT NULL,
  "sent" timestamptz NULL,
  "key" character varying(64) NOT NULL,
  "email_address_id" integer NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "account_emailconfirmation_key_key" UNIQUE ("key"),
  CONSTRAINT "account_emailconfirm_email_address_id_5b7f8c58_fk_account_e" FOREIGN KEY ("email_address_id") REFERENCES "public"."account_emailaddress" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "account_emailconfirmation_email_address_id_5b7f8c58" to table: "account_emailconfirmation"
CREATE INDEX "account_emailconfirmation_email_address_id_5b7f8c58" ON "public"."account_emailconfirmation" ("email_address_id");
-- Create index "account_emailconfirmation_key_f43612bd_like" to table: "account_emailconfirmation"
CREATE INDEX "account_emailconfirmation_key_f43612bd_like" ON "public"."account_emailconfirmation" ("key" varchar_pattern_ops);
-- Create "django_content_type" table
CREATE TABLE "public"."django_content_type" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "app_label" character varying(100) NOT NULL,
  "model" character varying(100) NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE ("app_label", "model")
);
-- Create "auth_permission" table
CREATE TABLE "public"."auth_permission" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying(255) NOT NULL,
  "codename" character varying(100) NOT NULL,
  "content_type_id" integer NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE ("content_type_id", "codename"),
  CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "public"."django_content_type" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "auth_permission_content_type_id_2f476e4b" to table: "auth_permission"
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "public"."auth_permission" ("content_type_id");
-- Create "auth_group" table
CREATE TABLE "public"."auth_group" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying(150) NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "auth_group_name_key" UNIQUE ("name")
);
-- Create index "auth_group_name_a6ea08ec_like" to table: "auth_group"
CREATE INDEX "auth_group_name_a6ea08ec_like" ON "public"."auth_group" ("name" varchar_pattern_ops);
-- Create "auth_group_permissions" table
CREATE TABLE "public"."auth_group_permissions" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "group_id" integer NOT NULL,
  "permission_id" integer NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE ("group_id", "permission_id"),
  CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "public"."auth_permission" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "public"."auth_group" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "auth_group_permissions_group_id_b120cbf9" to table: "auth_group_permissions"
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "public"."auth_group_permissions" ("group_id");
-- Create index "auth_group_permissions_permission_id_84c5c92e" to table: "auth_group_permissions"
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "public"."auth_group_permissions" ("permission_id");
-- Create "auth_user_groups" table
CREATE TABLE "public"."auth_user_groups" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "group_id" integer NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "auth_user_groups_user_id_group_id_94350c0c_uniq" UNIQUE ("user_id", "group_id"),
  CONSTRAINT "auth_user_groups_group_id_97559544_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "public"."auth_group" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "auth_user_groups_user_id_6a12ed8b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "auth_user_groups_group_id_97559544" to table: "auth_user_groups"
CREATE INDEX "auth_user_groups_group_id_97559544" ON "public"."auth_user_groups" ("group_id");
-- Create index "auth_user_groups_user_id_6a12ed8b" to table: "auth_user_groups"
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "public"."auth_user_groups" ("user_id");
-- Create "auth_user_user_permissions" table
CREATE TABLE "public"."auth_user_user_permissions" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "permission_id" integer NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" UNIQUE ("user_id", "permission_id"),
  CONSTRAINT "auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "public"."auth_permission" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "auth_user_user_permissions_permission_id_1fbb5f2c" to table: "auth_user_user_permissions"
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "public"."auth_user_user_permissions" ("permission_id");
-- Create index "auth_user_user_permissions_user_id_a95ead1b" to table: "auth_user_user_permissions"
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "public"."auth_user_user_permissions" ("user_id");
-- Create "django_admin_log" table
CREATE TABLE "public"."django_admin_log" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "action_time" timestamptz NOT NULL,
  "object_id" text NULL,
  "object_repr" character varying(200) NOT NULL,
  "action_flag" smallint NOT NULL,
  "change_message" text NOT NULL,
  "content_type_id" integer NULL,
  "user_id" integer NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "public"."django_content_type" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "django_admin_log_user_id_c564eba6_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "django_admin_log_action_flag_check" CHECK (action_flag >= 0)
);
-- Create index "django_admin_log_content_type_id_c4bce8eb" to table: "django_admin_log"
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "public"."django_admin_log" ("content_type_id");
-- Create index "django_admin_log_user_id_c564eba6" to table: "django_admin_log"
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "public"."django_admin_log" ("user_id");
-- Create "socialaccount_socialaccount" table
CREATE TABLE "public"."socialaccount_socialaccount" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "provider" character varying(200) NOT NULL,
  "uid" character varying(191) NOT NULL,
  "last_login" timestamptz NOT NULL,
  "date_joined" timestamptz NOT NULL,
  "extra_data" jsonb NOT NULL,
  "user_id" integer NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "socialaccount_socialaccount_provider_uid_fc810c6e_uniq" UNIQUE ("provider", "uid"),
  CONSTRAINT "socialaccount_socialaccount_user_id_8146e70c_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "socialaccount_socialaccount_user_id_8146e70c" to table: "socialaccount_socialaccount"
CREATE INDEX "socialaccount_socialaccount_user_id_8146e70c" ON "public"."socialaccount_socialaccount" ("user_id");
-- Create "socialaccount_socialapp" table
CREATE TABLE "public"."socialaccount_socialapp" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "provider" character varying(30) NOT NULL,
  "provider_id" character varying(200) NOT NULL,
  "name" character varying(40) NOT NULL,
  "client_id" character varying(191) NOT NULL,
  "secret" character varying(191) NOT NULL,
  "key" character varying(191) NOT NULL,
  "settings" jsonb NOT NULL,
  PRIMARY KEY ("id")
);
-- Create "socialaccount_socialtoken" table
CREATE TABLE "public"."socialaccount_socialtoken" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "token" text NOT NULL,
  "token_secret" text NOT NULL,
  "expires_at" timestamptz NULL,
  "account_id" integer NOT NULL,
  "app_id" integer NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq" UNIQUE ("app_id", "account_id"),
  CONSTRAINT "socialaccount_social_account_id_951f210e_fk_socialacc" FOREIGN KEY ("account_id") REFERENCES "public"."socialaccount_socialaccount" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "socialaccount_social_app_id_636a42d7_fk_socialacc" FOREIGN KEY ("app_id") REFERENCES "public"."socialaccount_socialapp" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "socialaccount_socialtoken_account_id_951f210e" to table: "socialaccount_socialtoken"
CREATE INDEX "socialaccount_socialtoken_account_id_951f210e" ON "public"."socialaccount_socialtoken" ("account_id");
-- Create index "socialaccount_socialtoken_app_id_636a42d7" to table: "socialaccount_socialtoken"
CREATE INDEX "socialaccount_socialtoken_app_id_636a42d7" ON "public"."socialaccount_socialtoken" ("app_id");
