mode: deployment
ports:
  otlp-http:
    servicePort: 80
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false
config:
  receivers:
    otlp:
      protocols:
        http:
          cors:
            allowed_origins:
            - "*"
  processors:
    batch:
      send_batch_max_size: 1000
      send_batch_size: 100
      timeout: 10s
  exporters:
    otlp/honey:
      endpoint: "api.honeycomb.io:443"
      headers:
        "x-honeycomb-team": "PKVsleMMnreKfWfsb69dwo"
    logging:
      verbosity: normal # can be normal, basic, or detailed
  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [logging, otlp/honey]
      metrics: null
