image:
  repository: "ewr.vultrcr.com/polytlk/web-client"
  tag: "sha-5b9df00"
env:
- name: BASE_URL
  value: https://dev.api.polytlk.io
- name: TARGET_ENV
  value: "development"
replicaCount: 1
imagePullSecrets: []
nameOverride: "web-client-svc"
fullnameOverride: "web-client-svc"
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  enabled: true
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: dev.polytlk.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: nginx-tls
      hosts:
        - dev.polytlk.io
resources: {}
autoscaling:
  enabled: false
nodeSelector: {}
tolerations: []
affinity: {}
volumeMounts:
  - mountPath: "/etc/nginx/ssl"
    name: nginx-tls
    readOnly: true
volumes:
  - name: nginx-tls
    secret:
      secretName: nginx-tls