image:
  repository: "ewr.vultrcr.com/polytlk/web-client"
  tag: "sha-c7234b1"
env:
- name: BASE_URL
  value: http://dev.api.polytlk.io
- name: TARGET_ENV
  value: "development"
replicaCount: 1
imagePullSecrets: []
nameOverride: "web-client-svc"
fullnameOverride: "web-client-svc"
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  enabled: true
  type: LoadBalancer
  port: 443
resources: {}
autoscaling:
  enabled: false
nodeSelector: {}
tolerations: []
affinity: {}
volumeMounts:
  - mountPath: "/etc/nginx/ssl"
    name: nginx-tls
    readOnly: true
volumes:
  - name: nginx-tls
    secret:
      secretName: nginx-tls