config:
  exporters:
    logging:
      verbosity: normal
    otlp/honey:
      endpoint: api.honeycomb.io:443
      headers:
        x-honeycomb-team: PKVsleMMnreKfWfsb69dwo
  processors:
    batch:
      send_batch_max_size: 1000
      send_batch_size: 100
      timeout: 10s
  receivers:
    otlp:
      protocols:
        http:
          cors:
            allowed_origins:
            - '*'
  service:
    pipelines:
      metrics: null
      traces:
        exporters:
        - logging
        - otlp/honey
        processors:
        - batch
        receivers:
        - otlp
extraEnvs:
- name: HONEYCOMB_API_KEY
  valueFrom:
    secretKeyRef:
      key: HONEYCOMB_API_KEY
      name: otel-collector-secret-env
mode: deployment
nodeSelector:
  role: ops
ports:
  jaeger-compact:
    enabled: false
  jaeger-grpc:
    enabled: false
  jaeger-thrift:
    enabled: false
  otlp-http:
    servicePort: 80
  zipkin:
    enabled: false
