apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: polytlk-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: git@github.com:polytlk/polytlk-cd.git
      revision: HEAD
      directories:
      - path: development/apps/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:polytlk/polytlk-cd.git
        targetRevision: HEAD
        path: '{{.path.path}}'
        directory:
            recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
