apiVersion: batch/v1
kind: Job
metadata:
  name: delete-apis-job
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: delete-apis
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              # Delete APIs
              kubectl delete apidefinition.tyk.tyk.io --all --namespace {{ .Release.Namespace }}

              # Remove finalizers
              for api in $(kubectl get apidefinition.tyk.tyk.io -o jsonpath='{.items[*].metadata.name}' --namespace {{ .Release.Namespace }}); do
                kubectl patch apidefinition.tyk.tyk.io $api --type=json -p='[{"op": "remove", "path": "/metadata/finalizers"}]' --namespace {{ .Release.Namespace }}
              done
      restartPolicy: OnFailure
