---
# Source: tyk-oss/charts/tyk-gateway/templates/deployment-gw-repset.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-tyk
  labels:
    app: gateway-tyk
    chart: tyk-gateway-1.6.0
    release: tyk-headless
    heritage: Helm
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    # indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: gateway-tyk
      release: tyk-headless
  template:
    metadata:
      annotations:
        checksum/secret: 68002deea5b1d005aed9d66004b95102c79ccd85e7f4514f1f3fce8b380bd4b3
      labels:
        app: gateway-tyk
        release: tyk-headless        
    spec:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      initContainers:
      - name: "setup-directories"
        image: "busybox:1.32"
        command: ['sh','-c','mkdir -p apps middleware policies && touch policies/policies.json']
        workingDir: /mnt/tyk-gateway
        securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault      
        resources:
            {}
        volumeMounts:
          - name: tyk-scratch
            mountPath: /mnt/tyk-gateway
      containers:
      - name: gateway-tyk-gateway
        image: "docker.tyk.io/tyk-gateway/tyk-gateway:v5.5.0"
        imagePullPolicy: IfNotPresent
        securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
        env:
          - name: TYK_GW_LISTENPORT
            value: "8080"
          
          - name: TYK_GW_OAS_VALIDATE_EXAMPLES
            value: "false"
          - name: TYK_GW_OAS_VALIDATE_SCHEMA_DEFAULTS
            value: "false"
          - name: TYK_GW_ENABLEFIXEDWINDOWRATELIMITER
            value: "false"
          
          # Redis TLS configurations            

          # Legacy support for Redis Cluster driver. Driver dropped in v3.0.0.
          - name: REDIGOCLUSTER_SHARDCOUNT
            value: "128"
          - name: TYK_GW_STORAGE_TYPE
            value: "redis"
          - name: TYK_GW_STORAGE_ADDRS
            value: "redis-master.default.svc.cluster.local:6379"
          
          - name: TYK_GW_STORAGE_ENABLECLUSTER
            value: "false"
         

          - name: TYK_GW_STORAGE_DATABASE
            value: "0"
          - name: TYK_GW_STORAGE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secrets-tyk
                key: redisPass
          - name: TYK_GW_STORAGE_USESSL
            value: "false"
          - name: TYK_GW_SECRET
            valueFrom:
              secretKeyRef:
                name:  secrets-tyk 
                key: APISecret
          - name: TYK_GW_NODESECRET
            valueFrom:
              secretKeyRef:
                name:  secrets-tyk 
                key: APISecret

          - name: TYK_GW_POLICIES_ALLOWEXPLICITPOLICYID
            value: "true"
          - name: TYK_GW_HTTPSERVEROPTIONS_USESSL
            value: "false"
          - name: TYK_GW_TEMPLATEPATH
            value: "/opt/tyk-gateway/templates"
          - name: TYK_GW_TYKJSPATH
            value: "/opt/tyk-gateway/js/tyk.js"
          - name: TYK_GW_MIDDLEWAREPATH
            value: "/mnt/tyk-gateway/middleware"
          - name: TYK_GW_APPPATH
            value: "/mnt/tyk-gateway/apps"
          - name: TYK_GW_POLICIES_POLICYPATH
            value: "/mnt/tyk-gateway/policies"
          - name: TYK_GW_STORAGE_MAXIDLE
            value: "1000"
          - name: TYK_GW_ENABLENONTRANSACTIONALRATELIMITER
            value: "true"
          - name: TYK_GW_POLICIES_POLICYSOURCE
            value: "file"

        # Set this environment variable only if either analyticsEnabled or global.components.pump is set
        

          - name: TYK_GW_ANALYTICSCONFIG_TYPE
            value: ""
          - name: TYK_GW_POLICIES_POLICYRECORDNAME
            value: "/mnt/tyk-gateway/policies/policies.json"
          - name: TYK_GW_HASHKEYS
            value: "true"
          - name: TYK_GW_HASHKEYFUNCTION
            value: "murmur128"
          - name: TYK_GW_HTTPSERVEROPTIONS_ENABLEWEBSOCKETS
            value: "true"
          - name: TYK_GW_HTTPSERVEROPTIONS_MINVERSION
            value: "771"
          - name: TYK_GW_HTTPSERVEROPTIONS_CERTIFICATES
            value: '[{"cert_file":"/etc/certs/tyk-gateway/tls.crt","domain_name":"*","key_file":"/etc/certs/tyk-gateway/tls.key"}]'
          - name: TYK_GW_HTTPSERVEROPTIONS_SSLINSECURESKIPVERIFY
            value: "false"
          - name: TYK_GW_ALLOWINSECURECONFIGS
            value: "true"
          - name: TYK_GW_COPROCESSOPTIONS_ENABLECOPROCESS
            value: "true"
          - name: TYK_GW_GLOBALSESSIONLIFETIME
            value: "100"
          - name: TYK_GW_MAXIDLECONNSPERHOST
            value: "500"
          - name: TYK_GW_ENABLECUSTOMDOMAINS
            value: "true"
          - name: TYK_GW_PIDFILELOCATION
            value: "/mnt/tyk-gateway/tyk.pid"
          - name: TYK_GW_DBAPPCONFOPTIONS_NODEISSEGMENTED
            value: "false"
          - name: TYK_GW_OPENTELEMETRY_ENABLED
            value: "true"
          - name: TYK_GW_OPENTELEMETRY_EXPORTER
            value: "http"
          - name: TYK_GW_OPENTELEMETRY_ENDPOINT
            value: "http://opentelemetry-collector.opentelemetry.svc.cluster.local/v1/traces"
          - name: TYK_GW_OPENTELEMETRY_CONNECTIONTIMEOUT
            value: "1"
          - name: TYK_GW_OPENTELEMETRY_RESOURCENAME
            value: "tyk-api-gateway"
          - name: TYK_GW_OPENTELEMETRY_SPANPROCESSORTYPE
            value: "batch"
          - name: TYK_GW_OPENTELEMETRY_CONTEXTPROPAGATION
            value: "tracecontext"

          - name: TYK_GW_OPENTELEMETRY_SAMPLING_TYPE
            value: "AlwaysOn"
          - name: TYK_GW_OPENTELEMETRY_SAMPLING_RATE
            value: "0.5"
          - name: TYK_GW_OPENTELEMETRY_SAMPLING_PARENTBASED
            value: "false"
          - name: TYK_GW_ENABLEJSVM
            value: "true"
          - name: TYK_GW_LOGLEVEL
            value: info
          - name: TYK_GW_POLICIES_POLICYSOURCE
            value: file
          - name: TYK_GW_POLICIES_POLICYPATH
            value: ""
          - name: TYK_GW_POLICIES_POLICYRECORDNAME
            value: /mnt/tyk-gateway/policies/policies.json
        workingDir: /opt/tyk-gateway
        ports:
        - containerPort: 8080
        resources:
            {}
        volumeMounts:
          

          - name: tyk-scratch
            mountPath: /mnt/tyk-gateway
          - mountPath: /mnt/tyk-gateway/policies
            name: policy-config
            readOnly: true
          - mountPath: /mnt/tyk-gateway/middleware
            name: sse-auth-pre-middleware
            readOnly: true
        livenessProbe:
          httpGet:
            scheme: "HTTP"
            path: /hello
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 3
          failureThreshold: 2
        readinessProbe:
          httpGet:
            scheme: "HTTP"
            path: /hello
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
      securityContext:
          fsGroup: 2000
          runAsNonRoot: true
          runAsUser: 1000
      volumes:
        - name: tyk-scratch
          emptyDir: {}
        
        - configMap:
            name: policy-config
          name: policy-config
        - configMap:
            name: sse-auth-pre-middleware-tbmcf478cg
          name: sse-auth-pre-middleware
