load('ext://helm_remote', 'helm_remote')
load('ext://cert_manager', 'deploy_cert_manager')
load('ext://secret', 'secret_from_dict')


# define tyk namespace
tyk_namespace = 'tyk'

# create the namespace using local command and kubectl
local('kubectl create namespace {} || true'.format(tyk_namespace))

helm_remote('tyk-headless',
            repo_name='tyk-helm',
            repo_url='https://helm.tyk.io/public/helm/charts/',
            namespace=tyk_namespace,
            values=['tyk.yaml']
)

system_namespace = 'tyk-operator-system'
local('kubectl create namespace {} || true'.format(system_namespace))

# deploy cert manager
deploy_cert_manager(version='v1.8.0')


# create the secret
k8s_yaml(secret_from_dict(
    name='tyk-operator-conf',
    namespace=system_namespace,
    inputs={
        'TYK_AUTH': 'CHANGEME', 
        'TYK_MODE': 'ce',
        'TYK_ORG': '5e9d9544a1dcd60001d0ed20',
        'TYK_URL': 'http://gateway-svc-tyk-headless.tyk.svc.cluster.local:8080',
        'TYK_TLS_INSECURE_SKIP_VERIFY': 'true'
    }
))

helm_remote('tyk-operator',
            repo_name='tyk-helm',
            repo_url='https://helm.tyk.io/public/helm/charts/',
            namespace=system_namespace,
            allow_duplicates=False
)

k8s_yaml('./apis/eden.yaml')