load('ext://helm_resource', 'helm_repo')

helm_repo(name='tyk-helm', url='https://helm.tyk.io/public/helm/charts/', labels=['helm'])

include('./operator/Tiltfile')
include('./apis/Tiltfile')

USE_TYK_PRO = os.environ.get('USE_TYK_PRO', False)

if USE_TYK_PRO:
    load_dynamic('./pro/Tiltfile')
else:
    load_dynamic('./ce/Tiltfile')