[tool.coverage.run]
branch = true
source = ["socrates"]

[tool.coverage.report]
exclude_lines = ['if TYPE_CHECKING:']
show_missing = true

[tool.pytest.ini_options]
addopts = "--cov --cov-fail-under=100 --cov-report html:'../../coverage/apps/socrates/html' --cov-report xml:'../../coverage/apps/socrates/coverage.xml' --junitxml='../../reports/apps/socrates/unittests/junit.xml' --html='../../reports/apps/socrates/unittests/html/index.html'"

[tool.poetry]
name = "socrates"
version = "1.0.0"
description = "Socrates: chatgpt microservice"
authors = []
license = 'Proprietary'
readme = 'README.md'

[[tool.poetry.packages]]
include = "socrates"

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
fastapi = "^0.95.2"
uvicorn = {extras = ["standard"], version = "^0.22.0"}
openai = "^0.27.8"

[tool.poetry.group.dev.dependencies]
autopep8 = "2.0.0"
wemake-python-styleguide = {git = "https://github.com/wemake-services/wemake-python-styleguide.git"}
mypy = "^1.3.0"

[tool.poetry.scripts]
start = "socrates.asgi:start"

[build-system]
requires = ["poetry-core==1.1.0"]
build-backend = "poetry.core.masonry.api"
