load('ext://namespace', 'namespace_create', 'namespace_inject')
load('ext://nerdctl', 'nerdctl_build')
load('ext://secret', 'secret_yaml_generic')

NAMESPACE = 'socrates'
namespace_create(NAMESPACE)

k8s_yaml(secret_yaml_generic('socrates-svc-secret-env', from_env_file='./.env', namespace=NAMESPACE))
k8s_yaml(namespace_inject(read_file('../../../tilt/socrates/deployment/deployment.yaml'), NAMESPACE))
k8s_yaml(namespace_inject(read_file('../../../tilt/socrates/deployment/service.yaml'), NAMESPACE))

k8s_resource(
    'socrates-svc',
    labels=["openai"],
    # UNCOMMENT to expose individual testing
    # port_forwards=8079
)

nerdctl_build('socrates-svc-img', '.',     
    live_update=[
        sync('.', '/code'),
        run('cd /code && poetry install --no-interaction --no-root --without dev',
            trigger=['./poetry.lock', './pyproject.toml']),
    ]
)


