load('ext://namespace', 'namespace_inject')
load('ext://podman', 'podman_build')

NAMESPACE='socrates'
TYK_PATH='../../../tilt/socrates'

k8s_yaml(namespace_inject(read_file('{0}/deployment/deployment.yaml'.format(TYK_PATH)), NAMESPACE))
k8s_yaml(namespace_inject(read_file('{0}/deployment/service.yaml'.format(TYK_PATH)), NAMESPACE))

k8s_resource(
    'socrates-svc',
    labels=["openai"],
    # UNCOMMENT to expose individual testing
    # port_forwards=8079
)

podman_build('socrates-svc-img', '.',
    extra_flags=[
        '--target',
        'development'
    ],
    live_update=[
        sync('./socrates', '/app/socrates')
    ]
)


