name: Merge Job
on:
  push:
    branches: [main]

jobs:
  execute:
    runs-on: ubuntu-latest
    name: execute
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ./.npmrc

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.9.0
          run_install: true

      - name: Get base commit SHA
        id: get-base
        run: echo "BASE_SHA=$(git log HEAD~1 -1 --format=%H)" >> "$GITHUB_OUTPUT"
  
      - run: pnpm nx show projects --affected --base=$BASE_SHA
        env:
          BASE_SHA: ${{ steps.get-base.outputs.BASE_SHA }}

      - run: pnpm nx show projects --affected --base=main~1

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          registry: https://ewr.vultrcr.com/polytlk
          username: 96d895d4-f075-42fa-b566-a8e22ba9007b
          password: ${{ secrets.VULTR_DOCKER_PASSWORD }}

      - run: pnpm nx affected -t container --base=$BASE_SHA --head=main 
        env:
          BASE_SHA: ${{ steps.get-base.outputs.BASE_SHA }}
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: pnpm nx affected -t template:dev --base=$BASE_SHA --head=main 
        env:
          BASE_SHA: ${{ steps.get-base.outputs.BASE_SHA }}