name: Build Service Image
on:
  workflow_dispatch:
    inputs:
      service_name:
        type: choice
        description: "Name of the service to build"
        required: true
        options: 
        - eden
        - eden-worker
        - heimdall
        - socrates

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.9.0
          run_install: true

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          registry: https://ewr.vultrcr.com/polytlk
          username: 96d895d4-f075-42fa-b566-a8e22ba9007b
          password: ${{ secrets.VULTR_DOCKER_PASSWORD }}

      - name: Docker build
        run: pnpm nx run ${{ inputs.service_name }}:container
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
