name: Nx Standard Use Case

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: # This line enables manual triggering

jobs:
  ci:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - run: pnpm install
    - run: pnpx nx run-many --target=test --all
    - run: pnpx nx run-many --target=lint --all
    - run: pnpx nx run-many --target=build --all --prod
