name: Pull Request job
on:
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Affected Matrix
    outputs:
      hasChanges: ${{ steps.affected.outputs.hasChanges }}
      matrix: ${{ steps.affected.outputs.matrix }}
    steps:
      - name: Calculate affected projects
        uses: e-square-io/nx-affected-matrix@v2
        id: affected
        with:
          targets: 'container,template,template:dev'
          maxDistribution: 10

  execute:
    runs-on: ubuntu-latest
    name: ${{ matrix.target }}
    if: ${{ fromJSON(needs.setup.outputs.hasChanges) }}
    needs: [setup]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ./.npmrc

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.9.0
          run_install: true

      - run: echo ${{ matrix.projects }}

      - run: echo ${{ matrix.target }}